
version: '3.9'
services:
  node:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '3000:3000'
    volumes:
      # - ./server:/app
      # # - ./app/node_modules
  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - '3001:3001'
    stdin_open: true
